In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [31]:
sentences = ["My name is Huy", "I have a passion for coding challenges", "The percentage of people who like coding is only 5 percent", "His name is Giang"]
dictionary = []
for sentence in sentences:
    dictionary+=(sentence.split(" "))
dictionary = list(map(lambda text: text.lower(), sorted(set(dictionary))))
dictionary

['5',
 'giang',
 'his',
 'huy',
 'i',
 'my',
 'the',
 'a',
 'challenges',
 'coding',
 'for',
 'have',
 'is',
 'like',
 'name',
 'of',
 'only',
 'passion',
 'people',
 'percent',
 'percentage',
 'who']

# Bag of words

In [32]:
def BagOfWords(sentence: str):
    words = sentence.split(" ")
    words = list(map(lambda text: text.lower(), words))
    results = np.zeros(len(dictionary))
    for word in words:
        for i, w in enumerate(dictionary):
            if w == word:
                results[i] += 1
    return results

for sentence in sentences:
    print(BagOfWords(sentence))


[0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
[0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


# N-Gram

In [52]:
from collections import Counter
def generate_n_gram(sentence, n):
    words = sentence.split(" ")
    words = list(map(lambda text: text.lower(), words))
    results = [tuple(words[i:i+n]) for i in range(len(words)-n+1)]
    return results
ngrams = generate_n_gram("Hanoi is larger than Ho Chi Minh City and Hanoi is", 2)
Counter(ngrams)

Counter({('hanoi', 'is'): 2,
         ('is', 'larger'): 1,
         ('larger', 'than'): 1,
         ('than', 'ho'): 1,
         ('ho', 'chi'): 1,
         ('chi', 'minh'): 1,
         ('minh', 'city'): 1,
         ('city', 'and'): 1,
         ('and', 'hanoi'): 1})

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
sentences = ["Hanoi is larger than Ho Chi Minh City", "Ho Chi Minh City is larger than Hanoi"]
vect = CountVectorizer(ngram_range=(2,2))
ngrams = vect.fit(sentences)
print(ngrams)
vect.vocabulary_

CountVectorizer(ngram_range=(2, 2))


{'hanoi is': 2,
 'is larger': 4,
 'larger than': 5,
 'than ho': 8,
 'ho chi': 3,
 'chi minh': 0,
 'minh city': 6,
 'city is': 1,
 'than hanoi': 7}

In [58]:
from scipy.spatial.distance import euclidean

vect = CountVectorizer(ngram_range = (3, 3), analyzer = 'char_wb')
n1, n2, n3, n4 = vect.fit_transform(['andersen', 'peterson', 'petrov', 'smith']).toarray()
print(n1, n2, n3, n4)
euclidean(n1, n2), euclidean(n2, n3), euclidean(n3, n4)

[1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0] [0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0] [0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1] [0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0]


(np.float64(3.7416573867739413),
 np.float64(3.1622776601683795),
 np.float64(3.3166247903554))

# TF-IDF

In [69]:
np.log(np.e)

np.float64(1.0)

In [72]:
sentences = ["sky blue",
             "sun bright today",
             "sun sky bright",
             "can see shining sun bright sun"]
def TF_IDF(docs):
    words = []
    for sentence in docs:
        words += sentence.split(" ")
    words = [word.lower() for word in words]
    totas_words = len(words)
    freqs = Counter(words)
    tf = freqs.copy()
    idf = freqs.copy()
    print(freqs)
    for f in freqs.keys():
        tf[f] = freqs[f] / totas_words
        idf[f] = np.log10(totas_words / freqs[f])
    return tf, idf
TF_IDF(sentences)


Counter({'sun': 4, 'bright': 3, 'sky': 2, 'blue': 1, 'today': 1, 'can': 1, 'see': 1, 'shining': 1})


(Counter({'sun': 0.2857142857142857,
          'bright': 0.21428571428571427,
          'sky': 0.14285714285714285,
          'blue': 0.07142857142857142,
          'today': 0.07142857142857142,
          'can': 0.07142857142857142,
          'see': 0.07142857142857142,
          'shining': 0.07142857142857142}),
 Counter({'blue': np.float64(1.146128035678238),
          'today': np.float64(1.146128035678238),
          'can': np.float64(1.146128035678238),
          'see': np.float64(1.146128035678238),
          'shining': np.float64(1.146128035678238),
          'sky': np.float64(0.8450980400142568),
          'bright': np.float64(0.6690067809585756),
          'sun': np.float64(0.5440680443502757)}))

In [75]:
np.log10(4/1)

np.float64(0.6020599913279624)